/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-01-22 07:17:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex03_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>내장객체</h1>\r\n");
      out.write("\t");

	//리퀘스트 : 웹 브라우저가 웹 서버에 전송한 요청 관련 정보 제공
	//javax.servlet.http.HttpServletRequest req = request;
	String addr = request.getRemoteAddr();
	System.out.println(addr);
	String url = request.getRequestURI(); // url 위치
	String ctxt = request.getContextPath(); //프로젝트 기준 루트
	String servername = request.getServerName();
	int serverport = request.getServerPort();
	
      out.write("\r\n");
      out.write("\t<p>내 아이피 : ");
      out.print(addr );
      out.write(' ');
      out.print(url );
      out.write(' ');
      out.print( ctxt);
      out.write(' ');
      out.print(servername );
      out.write(' ');
      out.print(serverport );
      out.write("</p>\r\n");
      out.write("\t<p><a href=\"ex04.jsp?id=xyz\">link1</a></p>\r\n");
      out.write("\t<p><a href=\"ex04.jsp?id=abc&pw=1234\">link2</a></p>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\"ex04.jsp\" method=\"post\">\r\n");
      out.write("\t<input type=\"text\" name=\"id\" value=\"abc\"><br>\r\n");
      out.write("\t<input type=\"password\" name=\"pw\"><br>\r\n");
      out.write("\t<input type=\"radio\" name=\"ra\" value=\"item1\" checked=\"checked\">item1\r\n");
      out.write("\t<input type=\"radio\" name=\"ra\" value=\"item2\">item2\r\n");
      out.write("\t<input type=\"radio\" name=\"ra\" value=\"item3\">item3<br>\r\n");
      out.write("\t<input type=\"checkbox\" name=\"ch\" value=\"ch1\">ch1\r\n");
      out.write("\t<input type=\"checkbox\" name=\"ch\" value=\"ch2\">ch2\r\n");
      out.write("\t<input type=\"checkbox\" name=\"ch\" value=\"ch3\">ch3\r\n");
      out.write("\t<input type=\"checkbox\" name=\"ch\" value=\"ch4\">ch4<br>\r\n");
      out.write("\t<select name=\"sel\">\r\n");
      out.write("\t\t<option value=\"02\">서울</option>\r\n");
      out.write("\t\t<option value=\"032\">대전</option>\r\n");
      out.write("\t\t<option value=\"042\">대구</option>\r\n");
      out.write("\t\t<option value=\"052\">부산</option>\r\n");
      out.write("\t\t<option value=\"062\">광주</option>\r\n");
      out.write("\t</select><br>\r\n");
      out.write("\t<select name=\"lst\" size=\"4\">\r\n");
      out.write("\t\t<option value=\"02\">서울</option>\r\n");
      out.write("\t\t<option value=\"032\">대전</option>\r\n");
      out.write("\t\t<option value=\"042\">대구</option>\r\n");
      out.write("\t\t<option value=\"052\">부산</option>\r\n");
      out.write("\t\t<option value=\"062\">광주</option>\r\n");
      out.write("\t</select><br>\r\n");
      out.write("\t<textarea rows=\"5\" cols=\"10\" name=\"ta\">value값이 없는 대신 여기에 쓰면 됨</textarea>\r\n");
      out.write("\t<input type=\"submit\" value=\"전송\">\r\n");
      out.write("\t<input type=\"reset\" value=\"취소\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
//쿼리를 자동으로 만들어줌 method="post" 쿼리숨겨서 보냄  이는 문서의 head부분에 보내는거임!!! method="get"이 디폴트
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
